### ISSUE TITLE
Inconsisten use of path while reading and writing to project file

### ISSUE THREAD

**Issue by FreeYourMinds** [process-engine/jenkins_shared-libraries#5]
The `prepare` step in the `Jenkinsfile-dotnet`file changes the directory 

> dir('dotnet')

and while the version is read from

> src/ProcessEngine.ConsumerAPI.Contracts.csproj

it is written back to 

> **dotnet**/src/ProcessEngine.ConsumerAPI.Contracts.csproj

See:
https://github.com/process-engine/consumer_api_contracts/blob/0bf685349503ebb2b44165806310512c9b35ef33/Jenkinsfile-dotnet#L31

This is at least inconsistent but might get a more serious issue when path handling is stricter at some point in the future.

**Comment by Paulomart** [comment]
I transferred this issue to the correct repo, but github broke the code references.

This will addressed when im back.

**Comment by FreeYourMinds** [comment]
Updates issue to be human readable again.
